# Stage 1: Development Mode
FROM node:20
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --silent
# COPY . .
EXPOSE 5173
EXPOSE 3000
CMD ["npm", "run", "dev"]

# # Stage 2: runtime
# FROM nginx:alpine
# COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]