# Stage 1: Development Build
FROM node:20-alpine AS runtime

WORKDIR /app

COPY . .

COPY package*.json ./
RUN npm ci

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

CMD ["npm", "run", "start:dev"]


# docker build -t backend -f ./backend/Dockerfile.dev ./backend
# docker run -d --name backend -p 8000:8080 -v $(pwd)/backend/src:/app/src:z --network agent_rag_qdrant_default -e ENV=development -e DEBUG=True backend
