# Stage 1: Development Build
FROM node:20-alpine AS runtime

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
ENV NODE_ENV=production
ENV PORT=8000

EXPOSE 8000

CMD ["npm", "run", "start:dev"]
