FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

EXPOSE 8001

# uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--port", "8002"]
